hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_connect:
    path: /connect/facebook

facebook_login:
    path: /login_facebook

app_settings:
    path: /settings
    defaults: { _controller: AppBundle:Default:edit }

app_home:
    path: /home
    defaults: { _controller: AppBundle:Default:home }

app_login_check:
    path: /login_check

app_logout:
    path: /logout

app_index:
    path: /
    defaults: { _controller: AppBundle:Default:index }
